spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  # hibernate를 사용해서 application이 실행할 때 데이터베이스 스키마를 변경하지 않게 해준다.
    database-platform: org.hibernate.dialect.H2Dialect

    sql:
      init:
        mode: always
        platform: h2


    database:
      url: jdbc:h2:mem:development;MODE=MYSQL;DB_CLOSE_DELAY=-1
      username: sa
      password:
      driverClassName: org.h2.Driver

    h2:
      console:
        enabled: true
        path: /h2-console